"""initial migration

Revision ID: 65e2b265fc84
Revises: 
Create Date: 2024-08-16 11:35:41.726868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e2b265fc84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('ski_level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Ski_gear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('camber_rocker', sa.Float(), nullable=True),
    sa.Column('tip', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('tail', sa.Float(), nullable=True),
    sa.Column('stiffness', sa.Float(), nullable=True),
    sa.Column('picture', sa.String(length=300), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('stability_vs_manoeuvrability', sa.Float(), nullable=True),
    sa.Column('short_vs_long_turns', sa.Float(), nullable=True),
    sa.Column('on_piste_vs_off_piste', sa.Float(), nullable=True),
    sa.Column('ski_level_min', sa.Float(), nullable=True),
    sa.Column('ski_level_max', sa.Float(), nullable=True),
    sa.Column('height_difference', sa.Float(), nullable=True),
    sa.Column('contact_length', sa.Float(), nullable=True),
    sa.Column('floatation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Ski_gear')
    op.drop_table('user')
    # ### end Alembic commands ###
